name: Generate docs and format

on:
  push:
    branches:
      - master
  pull_request_target:

jobs:
  postprocessing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      - uses: nixbuild/nix-quick-install-action@v30
      - run: nix develop -i -c bash -c 'make doc'

      - name: Ignore doc date-only changes
        run: |
          # Get "<added> <deleted>" for doc/luasnip.txt, e.g. "1 1"
          changed="$(git diff --numstat -- doc/luasnip.txt | awk '{print $1, $2}')"

          if [[ "$changed" == "1 1" ]]; then
            echo "doc/luasnip.txt: 1 added, 1 deleted -> assuming date-only change, revert diff"
            git restore doc/luasnip.txt
          else
            echo "doc/luasnip.txt: change is not exactly 1/1, keeping diff"
          fi

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto generate docs"
      - name: "Format with Stylua"
        uses: JohnnyMorganz/stylua-action@v1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.15.1
          args: .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Format with stylua"
